CetpaLiveProject/urls.py
from django.contrib import admin
from django.urls import path, include
from .import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emsapp/', include('EMS.urls')),
    path('lmsapp/', include('LMS.urls')),
    path('myapp/', include('myapp.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EMS/urls.py
from django.urls import path
from .views import *
# Base URL --> http://127.0.0.1:8000/emsapp

urlpatterns = [
    path('', home ),
    path('employee_record/', employee_record ),

]

myapp/urls.py
from django.urls import path
from .views import *


urlpatterns = [

    path('register', view_register, name='register'),
    path('login', view_login, name='login'),
    path('', all_student, name='all_student'),
    path('student_payment/', student_payment, name="student_payment"),
    path('student_reg/', student_reg, name="student_reg"),
    path('all_courses/', all_courses, name='all_courses'),
    path('course_student/', course_student, name="course_student"),
    path('course_reg/', course_reg, name='course_reg'),
    path('all_payment/', all_payment, name='all_payment'),
    path('PaymentDetails_reg/', PaymentDetails_reg, name='PaymentDetails_reg'),
    path('showstu/<int:id>/', view_show_student, name='showstu'),
]

EMS/models.py
from django.db import models


class Employee(models.Model):
    name = models.CharField(max_length=255)
    age = models.IntegerField()
    city = models.CharField(max_length=100)
    mobileno = models.CharField(max_length=50)
    salary = models.IntegerField()

    def __str__(self):
        return self.name

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Student(models.Model):
    pic = models.ImageField(upload_to='student')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    dob = models.DateField()
    mobileno = models.CharField(max_length=15)
    email = models.EmailField()
    address = models.TextField()

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=100)
    students = models.ManyToManyField(Student, null=True, blank=True)

    def __str__(self):
        return self.name


class PaymentDetails(models.Model):
    amount = models.IntegerField()
    payment_mode = models.CharField(max_length=100, choices=[('Cash','Cash'), ('Debit Card','Debit Card'), ('Credit Card','Credit Card'),('UPI','UPI')])
    payment_date = models.DateTimeField(auto_now=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

myapp/forms.py
from typing import Any, Dict, Mapping, Optional, Type, Union
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from .models import *


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = f'Enter {field.label} *'

        # self.fields['name'].widget.attrs.update({'class':'abc'})


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = f'Enter {field.label} *'


class PaymentDetailsForm(forms.ModelForm):
    class Meta:
        model = PaymentDetails
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = f'Enter {field.label} *'

myapp/views.py
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User, Group,Permission
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *


def view_register(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == "POST":
        user_form = UserCreationForm(request.POST, label_suffix='')
        student_form = StudentForm(request.POST, label_suffix='')
        if user_form.is_valid() and student_form.is_valid():
            user = user_form.save()
            user.is_staff = True
            user.save()
            g1 = Group.objects.get(id=1)
            user.groups.add(g1)
            student = student_form.save(commit=False)
            student.user = user
            student.save()
            return HttpResponse('<h1>User Registration Successfully.')
    else:
        user_form = UserCreationForm(label_suffix='')
        student_form = StudentForm(label_suffix='')

    return render(request, 'myapp/register.html', locals())


def view_login(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':

        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('secure1')
    else:
        form = AuthenticationForm()
    return render(request, 'myapp/login.html', locals())


def all_student(request):
    students = Student.objects.all()
    d1 = {'students':students}
    return render(request, 'myapp/all_student.html', context=d1)


def all_payment(request):
    payments = PaymentDetails.objects.all()
    d1 = {'payments':payments}
    return render(request, 'myapp/all_payment.html', context=d1)


def student_payment(request):
    if request.method == "GET":
        return render(request, 'myapp/student_payment.html')

    elif request.method == "POST":
        try:
            id = request.POST.get('id')
            student = Student.objects.get(id = id)
            payments = student.paymentdetails_set.all()

            d1 = {'student': student, 'payments':payments}
        except Student.DoesNotExist:
            d1 = {'error': 'Student Does not exist.'}
    return render(request, 'myapp/student_payment.html', context=d1)


def student_reg(request):
    if request.method == "GET":
        frm_unbound = StudentForm()
        d1 = {'form':frm_unbound}
        return render(request, 'myapp/student_reg.html', context=d1)

    elif request.method == 'POST':
        frm_bound = StudentForm(request.POST, files=request.FILES)
        if frm_bound.is_valid:
            frm_bound.save()
            return HttpResponse("Student Added Successfully.")
        else:
            d1 = {'form':frm_bound}
        return render(request, 'myapp/student_reg.html', context=d1)


def all_courses(request):
    courses = Course.objects.all()
    d1 = {'courses':courses}
    return render(request, 'myapp/all_courses.html', context=d1)


def course_reg(request):
    if request.method == "GET":
        frm_unbound = CourseForm()
        d1 = {'form':frm_unbound}
        return render(request, 'myapp/course_reg.html', context=d1)

    elif request.method == 'POST':
        frm_bound = CourseForm(request.POST)
        if frm_bound.is_valid:
            frm_bound.save()
            return HttpResponse("Course Added Successfully.")
        else:
            d1 = {'form':frm_bound}
        return render(request, 'myapp/course_reg.html', context=d1)


def PaymentDetails_reg(request):
    if request.method == "GET":
        frm_unbound = PaymentDetailsForm()
        d1 = {'form':frm_unbound}
        return render(request, 'myapp/payment_registration.html', context=d1)

    elif request.method == 'POST':
        frm_bound = PaymentDetailsForm(request.POST)
        if frm_bound.is_valid:
            frm_bound.save()
            return HttpResponse("Payment Added Successfully.")
        else:
            d1 = {'form':frm_bound}
        return render(request, 'myapp/payment_registration.html', context=d1)


def course_student(request):
    if request.method == "GET":
        return render(request, 'myapp/course_student.html')

    elif request.method == "POST":
        try:
            cid = request.POST.get('id')
            course = Course.objects.get(id=cid)
            students = course.students.all()

            d1 = {'course': course, 'students': students}
        except Course.DoesNotExist:
            d1 = {'error': 'Course Does not exist.'}
    return render(request, 'myapp/course_student.html', context=d1)



def view_show_student(request, id):
    stu = Student.objects.get(id=id)
    d1 = {'stu':stu}
    return render(request, 'myapp/showstu.html', context=d1)

templates/myapp/all_courses.html
{% extends 'base.html' %}
{% block title %}All Courses{% endblock title %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col">

    <table class="table table-bordered my-3 text-center">
        <tr>
            <td class="bg-primary text-light h3" colspan="7">List of Courses</td>
        </tr>
        <tr>
            <th style="width:50%">ID</th>
            <th style="width:50%">Name</th>
            {% comment %} <th>Students</th> {% endcomment %}
        </tr>
        {% for course in courses %}
        <tr>
            <td>{{course.id}}</td>
            <td>{{course.name}}</td>
            {% comment %} <td>
                <ul>
                    {% for s in course.students.all %}
                        <li>{{s}}</li>
                    {% endfor %}
                </ul>
            </td> {% endcomment %}
        </tr>
        {% endfor %}
    </table>
</div>
</div>
</div>

{% endblock main %}

templates/myapp/all_payment.html
{% extends 'base.html' %}
{% block title %}All Courses{% endblock title %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col">

    <table class="table table-bordered my-3 text-center">
        <tr>
            <td class="bg-primary text-light h3" colspan="7">List of Payment</td>
        </tr>
        <tr>
            <th style="width:25%">ID</th>
            <th style="width:25%">Amount</th>
            <th style="width:25%">Payment Mode</th>
            <th style="width:25%">Payment Date</th>
            {% comment %} <th>Students</th> {% endcomment %}
        </tr>
        {% for payment in payments %}
        <tr>
            <td>{{payment.id}}</td>
            <td>{{payment.amount}}</td>
            <td>{{payment.payment_mode}}</td>
            <td>{{payment.payment_date}}</td>
            {% comment %} <td>
                <ul>
                    {% for s in course.students.all %}
                        <li>{{s}}</li>
                    {% endfor %}
                </ul>
            </td> {% endcomment %}
        </tr>
        {% endfor %}
    </table>
</div>
</div>
</div>

{% endblock main %}

templates/myapp/all_student.html
{% extends 'base.html' %}
{% load static %}
{% block title %}SMS Home{% endblock title %}

{% block style %}{% endblock style %}
{% block main %}
    <div class="container">
        <div class="row">
            <div class="col">
                {% if students %}
                    <div class="table-responsive">
                        <table class="table my-3">
                            <tbody>
                            <tr>
                                <td class="h3 bg-success text-light text-center" colspan="8" >List of Student</td>
                            </tr>
                            <tr >
                                <th>ID</th>
                                <th>Image</th>
                                <th>Name</th>
                                <th>Age</th>
                                <th>Mobile No</th>
                                <th>Date of Birth</th>
                                <th>Create Date</th>
                                <th>Last Update</th>
                            </tr>
                            {% for student in students %}
                            <tr>
                                <td>{{student.id}}</td>
                                {% comment %} <td><img src="{{student.pic}}" alt="{{student.pic}}" height="100px"></td> {% endcomment %}
                                <td><img src="{{student.pic.url}}" alt="{{student.pic.url}}" height='50px' width='50px' style="border-radius:50%;"></td>
                                <td>{{student.name}}</td>
                                <td>{{student.age}}</td>
                                <td>{{student.mobileno}}</td>
                                <td>{{student.dob}}</td>
                                <td>{{student.create_date}}</td>
                                <td>{{student.last_update}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>

                        </table>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock main %}

templates/myapp/course_reg.html
{% extends 'base.html' %}


{% block main %}

<div class="container">
    <div class="row my-4 bg-light">
        <div class="col col-7 m-auto  rounded ">
            <h3 class='text-center pt-3'>Course Form</h3>
            <form action="" method="post">
                {% csrf_token %}
                <div class="from-group p-2">
                    <label for="id_name" class='py-1'>Amount</label>
                    {{form.name}}
                </div>
                <div class="from-group p-2">
                    <label for="id_students" class='py-1'>Student</label>
                    {{form.students}}
                </div>
                <div class="form-group py-3 p-2">
                    <input type="submit" class="btn btn-success w-100" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>  
{% endblock main %} 

templates/myapp/course_student.html
{% extends 'base.html' %}

{% block main %}
<div class="container ">
    <div class="row">
        <div class="col">
            <h1 class="text-center my-2 p-2 alert alert-primary">Course Student</h1>
        </div>
    </div>
    {% if course %}
    <div class="row">
        <div class="col">
                {% comment %} <h3  align='center' class="alert alert-warning">Student Details</h3> {% endcomment %}
                <table class="table table-bordered text-center">
                    <tr>
                        <td colspan='4' class="h4 bg-primary text-light">Course Details</td>
                    </tr>
                    <tr>
                        <th>ID</th>
                        <td>{{course.id}}</td>
                        <th>Name</th>
                        <td>{{course.name}}</td>
                    </tr>
                    
                </table>

                <table class="table table-bordered text-center">
                    <tr>
                        <td colspan='5' class="h4 bg-primary text-light">Student Details</td>
                    </tr>
                    <tr>
                        <th>S.No</th>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Mobile No</th>
                        <th>Date of Birth</th>
                    </tr>
                    {% for student in students %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{student.name}}</td>
                        <td>{{student.age}}</td>
                        <td>{{student.mobileno}}</td>
                        <td>{{student.dob}}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        {% else %}
        <div class="row">
            <div class="col-md-6 m-auto shadow p-4 rounded-4 border mt-4 bg-light">
                <form method="post" >
                    {% csrf_token %}
                    <label for="id" class="form-label">Course ID</label>
                    <input type="text" name="id" id="id" class="form-control mb-3" placeholder="Enter Course ID">
                    <input type="submit" class="btn btn-primary w-100" value="Submit">
                </form> 
            </div>
        </div>
        {% endif %}           
    </div>
{% endblock main %}

templates/myapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <style>
        input, textarea {
            border: 1px solid #ccc;
            border-radius:5px;
            padding: 5px;
            transition: border-color 0.3s;
        }
        input:focus, textarea:focus {
            border:2px solid #7df9ff;
            outline: none;
            position: relative;
            box-shadow: 0 0px 10px #7df9ff;
        }
        .errorlist{
            color:red;
        }
        .help_text{
            color:green;
        }
    </style
</head>
<body bgcolor="yellow">
<div class="container">
        <div class="row">
            <h1 align='center'>Welcome to LMS Login Page</h1>
        </div>
        <div class="row">
            <div class="col col-md-8 m-auto">
                <form action="" method="post" class="row g-3 needs-validation border rounded m-3 p-4" novalidate>
                    {% csrf_token %}
                    <table bgcolor='white' align='center'>
                        {{form.username.label_tag}}
                        {{form.username}}
                        <div class="help_text">
                            {{form.username.help_text}}
                        </div>
                        {{form.username.errors}}


                        {{form.password.label_tag}}
                        {{form.password}}
                        <div class="help_text">
                            {{form.password.help_text}}
                        </div>
                        {{form.password.errors}}
                        <tr>
                            <td>
                                <input type="submit" value="Register">
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
</div>
    <a href="{% url 'home' %}">Back To Home</a>
</body>
</html>

templates/myapp/payment_registration.html
{% extends 'base.html' %}


{% block main %}
<div class="container">
    <div class="row my-4">
        <div class="col col-7 m-auto bg-light rounded ">
            <h3 class='text-center pt-3'>Payment Form</h3>
            <form action="" method="post">
                {% csrf_token %}
                <div class="from-group p-2">
                    <label for="id_amount" class='py-1'>Amount</label>
                    {{form.amount}}
                </div>
                <div class="from-group p-2">
                    <label for="id_payment_mode" class='py-1'>Payment Mode</label>
                    {{form.payment_mode}}
                </div>
                <div class="from-group p-2">
                    <label for="id_student" class='py-1'>Student</label>
                    {{form.student}}
                </div>
                <div class="form-group py-3 p-2">
                    <input type="submit" class="btn btn-success w-100" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>  
{% endblock main %} 

templates/myapp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <style>
        input, textarea {
            border: 1px solid #ccc;
            border-radius:5px;
            padding: 5px;
            transition: border-color 0.3s;
        }
        input:focus, textarea:focus {
            border:2px solid #7df9ff;
            outline: none;
            position: relative;
            box-shadow: 0 0px 10px #7df9ff;
        }
        .errorlist{
            color:red;
        }
        .help_text{
            color:green;
        }
    </style>
</head>
<body  bgcolor="yellow">
    <div class="container">
        <div class="row">
            <h1 align='center'>Welcome to LMS Registration Page</h1>
        </div>
        <div class="row">
            <div class="col col-md-8 m-auto">
                <form action="" method="post" class="row g-3 needs-validation border rounded m-3 p-4" novalidate>
                    {% csrf_token %}
                    <table bgcolor='white' align='center'>

                        {{user_form.username.label_tag}}
                        {{user_form.username}}
                        <div class="help_text">
                            {{user_form.username.help_text}}
                        </div>
                        {{user_form.username.errors}}

                        {{student_form.name.label_tag}}
                        {{student_form.name}}
                        <div class="help_text">
                        {{student_form.name.help_text}}
                        </div>
                        {{student_form.name.errors}}

                        {{student_form.dob.label_tag}}
                        {{student_form.dob}}
                        <div class="help_text">
                        {{student_form.dob.help_text}}
                        </div>
                        {{student_form.dob.errors}}

                        {{student_form.mobileno.label_tag}}
                        {{student_form.mobileno}}
                        <div class="help_text">
                        {{student_form.mobileno.help_text}}
                        </div>
                        {{student_form.mobileno.errors}}

                        {{student_form.email.label_tag}}
                        {{student_form.email}}
                        <div class="help_text">
                        {{student_form.email.help_text}}
                        </div>
                        {{student_form.email.errors}}

                        {{student_form.address.label_tag}}
                        {{student_form.address}}
                        <div class="help_text">
                        {{student_form.address.help_text}}
                        </div>
                        {{student_form.address.errors}}

                        {{user_form.password1.label_tag}}
                        {{user_form.password1}}
                        <div class="help_text">
                        {{user_form.password1.help_text}}
                        </div>
                        {{user_form.password1.errors}}

                        {{user_form.password2.label_tag}}
                        {{user_form.password2}}
                        <div class="help_text">
                            {{user_form.password2.help_text}}
                        </div>
                        {{user_form.password2.errors}}

                        <tr>
                            <td>
                                <input type="submit" value="Register">
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>



    <a href="{% url 'home' %}">Back To Home</a>

</body>
</html>

templates/myapp/show_stu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table>
        <tr>
            <th>Name</th>
            <th>Name</th>
            <th>Age</th>
            <th>Age</th>
            <th>Mobile NO</th>
            <th>Mobile NO</th>
            <th>DOB</th>
            <th>DOB</th>
            <th>PIC</th>
            <th>PIC</th>
        </tr>
    </table>
</body>
</html>

templates/myapp/showstu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Show HTML</title>
</head>
<body>
    <h1 align='center'>Show Student Record</h1>
    <table border='3' align='center' width='50%'>
        <tr>
            <th>Name</th>
            <th>{{stu.name}}</th>
        </tr>
        <tr>
            <th>Age</th>
            <th>{{stu.age}}</th>
        </tr>
        <tr>
            <th>Mobile No</th>
            <th>{{stu.mobileno}}</th>
        </tr>
        <tr>
            <th>Date of Birth</th>
            <th>{{stu.dob}}</th>
        </tr>
        <tr>
            <th>Picture</th>
            <th>
                <img src="{{stu.pic.url}}" alt="{{stu.pic.url}}" height='200px'>
            </th>
        </tr>
    </table>
</body>
</html>

templates/myapp/student_payment.html
{% extends 'base.html' %}

{% block main %}
<div class="container ">
    <div class="row">
        <div class="col">
            <h1 class="text-center my-2 p-2 alert alert-primary">Student Payment Detail</h1>
        </div>
    </div>
    {% if student %}
    <div class="row">
        <div class="col">
                
                <table class="table table-bordered text-center">
                    <tr>
                        <td colspan='4' class="h4 bg-primary text-light">Student Details</td>
                    </tr>
                    <tr>
                        <th>ID</th>
                        <th>{{student.id}}</th>
                        <td rowspan='4' colspan='2' >
                            <img src="{{student.pic.url}}" alt="{{stu.pic.url}}" height='200px'>
                        </td>
                    </tr>
                    <tr>
                        <th>Name</th>
                        <td>{{student.name}}</td>
                    </tr>
                    <tr>
                        <th>Age</th>
                        <td>{{student.age}}</td>
                    </tr>
                    <tr>
                        <th>Mobile No</th>
                        <td>{{student.mobileno}}</td>
                    </tr>
                    <tr>
                        <th>Create Date</th>
                        <td>{{student.create_date}}</td>
                        <th>Create Date</th>
                        <td>{{student.create_date}}</td>
                    </tr>
                </table>

                <table class="table table-bordered text-center">
                    <tr>
                        <td colspan='4' class="h4 bg-primary text-light">Payment Details</td>
                    </tr>
                    <tr>
                        <th>S.No</th>
                        <th>Amount</th>
                        <th>Payment Mode</th>
                        <th>Payment Date</th>
                    </tr>
                    {% for payment in payments %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{payment.amount}}</td>
                        <td ><p class='badge text-bg-success'>{{payment.payment_mode}}</p></td>
                        <td>{{payment.payment_date}}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        {% else %}
        <div class="row">
            <div class="col-md-6 m-auto shadow p-4 rounded-4 border mt-4">
                <form method="post" >
                    {% csrf_token %}
                    <label for="id" class="form-label">Student ID</label>
                    <input type="text" name="id" id="id" class="form-control mb-3" placeholder="Enter Student ID">
                    <input type="submit" class="btn btn-primary w-100" value="Submit">
                </form> 
            </div>
        </div>
        {% endif %}           
    </div>
{% endblock main %}

templates/myapp/student_reg.html
{% extends 'base.html' %}
{% block main %}
<div class="container">
    <div class="row my-4">
        <div class="col col-7 m-auto bg-light rounded ">
            <h3 class='text-center pt-3'>Student Registration Form</h3>
            <form action="" method="post" enctype='multipart/form-data'>
                {% csrf_token %}
                <div class="from-group p-2">
                    <label for="id_name" class='py-1'>Name</label>
                    {{form.name}}
                </div>
                <div class="from-group p-2">
                    <label for="id_age" class='py-1'>Age</label>
                    {{form.age}}
                </div>
                <div class="from-group p-2">
                    <label for="id_mobileno" class='py-1'>Mobile No</label>
                    {{form.mobileno}}
                </div>
                <div class="from-group p-2">
                    <label for="id_dob" class='py-1'>Date of Birth</label>
                    {{form.dob}}
                </div>
                <div class="from-group p-2">
                    <label for="id_pic" class='py-1'>Photo</label>
                    {{form.pic}}
                </div>
                <div class="form-group py-3 p-2">
                    <input type="submit" class="btn btn-primary w-100" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock main %}